name: api

on:
  push:

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v1.1
      - run: nuget restore
      - name: Build app for release
        run: msbuild WindowsImage.sln -verbosity:diag -property:Configuration=Release

